[package]
name = "arc-cow"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/arthur-zhang/arc-cow"
keywords = ["arc", "cow"]
authors = [
    "Arthur Zhang <happyzhangya@gmail.com>",
]
[dependencies]
